name: My first Github Action
on: [push] #when this particular action should run

jobs: #jobs can be multiple and one job is not dependent on another job
    build-app:
        runs-on: ubuntu-latest
        env:
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}  
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}  
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} 
        steps: #one job can have multiple steps and its an array because we want run it sequentially
        - uses: actions/checkout@v2 #to checkout repo
        - uses: actions/setup-node@v2
          with: #to specify version
            node-version: '14.17.0'

        - name: Install node_modules
          run: yarn
        - name: Build the project
          run: yarn build
        - name: Sets the vercel env
          run: |
            cd build
            mkdir .vercel
            cd .vercel
            touch project.json
            echo "{\"projectId\":\"$VERCEL_PROJECT_ID\",\"orgId\":\"$VERCEL_ORG_ID\"}" > project.json
        - name: Deployint the project 
          run: yarn deploy
        - name: Setup finish
          run: echo "hurray!!"

    test-app:
        needs: build-app #now its gonna wait for build-app job to finished. 
        runs-on: ubuntu-latest
        steps:
            - run: echo "YOLO"

