name: My first Github Action
on: [push] #when this particular action should run

jobs: #jobs can be multiple and one job is not dependent on another job
  print-hello-world:
    runs-on: ubuntu-latest
    steps: #one job can have multiple steps and its array because we want run it sequentially
      - run: echo "!!!!!!!!!!!!!!!!!! hello world !!!!!!!!!!!!!!!!!!"
      - run: echo "this is second step"
  print-hello-world2:
    runs-on: ubuntu-latest
    steps: #one job can have multiple steps and its array because we want run it sequentially
      - run: echo "!!!!!!!!!!!!!!!!!! hello world !!!!!!!!!!!!!!!!!!"
      - run: echo "this is second step"
